@echo off
echo Starting JollofAI Development Servers...
echo.
echo Starting Frontend Server (Vite)...
start "Frontend" cmd /k "cd /d %~dp0 && npm run dev"
echo.
echo Waiting 5 seconds...
timeout /t 5 /nobreak > nul
echo.
echo Starting Mock API Server...
start "Mock API" cmd /k "cd /d %~dp0 && node mock-api-server.cjs"
echo.
echo Both servers are starting...
echo Frontend: http://localhost:5173
echo Mock API: http://localhost:3001
echo.
echo Press any key to continue...
pause > nul